### ISSUE TITLE
Authentication Problems? Try this

### ISSUE THREAD

**Issue by mitchellkrogza** [sferik/t#414]
Anyone having authentication problems can now easily fix it by doing this. Without even trying to go through the usual authentication method.

Simple create a `.trc` file in your home folder. 

`nano ~/.trc`

The format of the file is as follows.

```
---
profiles:
  my_username:
    1fakeFAKEfakeFAKEfakeFAKE3:
      username: my_username
      consumer_key: 1fakeFAKEfakeFAKEfakeFAKE3
      consumer_secret: fakeFAKEfakeFAKEfakeFAKEfakeFAKEfakeFAKE
      token: 123456789101112-fakeFakefakeFAKEfake
      secret: fakeFAKEfakeFAKEfakeFAKEfakeFAKEfakeFAKEfakeFAKEfakeFAKE
configuration:
  default_profile:
  - my_username
  - 1fakeFAKEfakeFAKEfakeFAKE3
```

The Twitter Developer API allows you to create the tokens without going through the usual process involving the pin.

Simple replace the contents of your .trc file with the appropriate keys and secrets

![2019-08-10_11-34](https://user-images.githubusercontent.com/9961541/62820340-2a755600-bb63-11e9-931b-df1a4c9f0e65.png)
